apiVersion: v2
name: ussdchannel
description: API for managing USSD short codes
type: application
version: 0.1.0
appVersion: v1

dependencies:
- name: micro
  version: 0.1.0
  repository: "https://raw.githubusercontent.com/gidyon/services/master/deployments/helm/packages"
